version: 0.2

env:
  variables:
    # that should be overriden during build
    LAMBDA: "default"
phases:
  install:
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - cd "lambdas/$LAMBDA"
      - mkdir -p dist
  build:
    commands:
      - chalice package dist
  post_build:
    commands:
      # deploy os here
      # seems too bad to me
      - aws lambda update-function-code --function-name $LAMBDA --zip-file fileb://lambdas/$LAMBDA/dist/deployment.zip
artifacts:
  files:
    - '$LAMBDA/dist/deployment.zip'
  discard-paths: yes
  base-directory: 'lambdas'

  